name: pacer
description: A new Flutter project.


publish_to: 'none' 


version: 3.5.49+49

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  geolocator: ^9.0.2
  dio: ^5.3.2
  geocoding: ^2.1.0
  flutter_compass: ^0.7.0
  alxgration_speedometer: ^0.0.2
  permission_handler: ^10.4.3
  pedometer: ^4.0.1
  google_maps_flutter: ^2.3.0
  intl: ^0.18.0
  connectivity_plus: ^4.0.2
  flutter_polyline_points: ^1.0.0
  percent_indicator: ^4.2.3
  path_provider: ^2.0.15
  fluttertoast: ^8.2.2
  syncfusion_flutter_charts: ^22.2.7
  flutter_vector_icons: ^2.0.0
  shared_preferences: ^2.2.0
  animate_do: ^3.0.2
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  firebase_core: ^2.15.1
  flutter_background_service: ^2.1.3
  device_info_plus: ^9.0.3
  flutter_fgbg: ^0.3.0
  google_mobile_ads: ^3.0.0
  firebase_crashlytics: ^3.3.2
  google_sign_in: ^6.1.4
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.6
  url_launcher: ^6.1.13
  share_plus: ^7.1.0
  device_preview: ^1.1.0
  upgrader: ^8.1.0
  firebase_analytics: ^10.4.5
  applovin_max: ^3.2.0
  # location: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
 
flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/Places/
    - assets/flags/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        

